-- # 【创建数据库】
create database if not exists kudu_sit_ods_prodccsdb;

-- # 【删除表】
drop table if exists kudu_sit_ods_prodccsdb.ccs_channel_info;
drop table if exists kudu_sit_ods_prodccsdb.ccs_loan;
drop table if exists kudu_sit_ods_prodccsdb.ccs_loan_reg;
drop table if exists kudu_sit_ods_prodccsdb.ccs_loan_reg_hst;
drop table if exists kudu_sit_ods_prodccsdb.ccs_acct;
drop table if exists kudu_sit_ods_prodccsdb.ccs_plan;
drop table if exists kudu_sit_ods_prodccsdb.ccs_customer;
drop table if exists kudu_sit_ods_prodccsdb.ccs_order;
drop table if exists kudu_sit_ods_prodccsdb.ccs_order_hst;
drop table if exists kudu_sit_ods_prodccsdb.ccs_loan_bal_rpt;
drop table if exists kudu_sit_ods_prodccsdb.ccs_overdue_hst_rpt;
drop table if exists kudu_sit_ods_prodccsdb.tpl_customer;
drop table if exists kudu_sit_ods_prodccsdb.tpl_loan_info;
drop table if exists kudu_sit_ods_prodccsdb.tpl_repay_info;
drop table if exists kudu_sit_ods_prodccsdb.tpl_trade_register;
drop table if exists kudu_sit_ods_prodccsdb.tpl_txn_register;

---------------【账务表】-------------------------
CREATE TABLE if not exists kudu_sit_ods_prodccsdb.ccs_channel_info(
	CHANNEL_ID				STRING
	, DB_CR_IND 			STRING
	, CHANNEL_NAME			STRING
	, SETTLE_TYPE 			STRING
	, CREATE_TIME 			STRING
	, FEE_TYPE 				STRING
	, FEE_VALUE 			DECIMAL(20, 6)
	, BIGDATA_DEL_STATUS	INT
	, BIGDATA_SYNC_TIME		BIGINT
	, PRIMARY KEY(CHANNEL_ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.ccs_loan(
	LOAN_ID 						INT
	, ORG							STRING
	, ACCT_NBR						BIGINT
	, ACCT_TYPE 					STRING
	, REF_NBR 						STRING
	, DUE_BILL_NO 					STRING
	, LOGIC_CARD_NBR 				STRING
	, CARD_NBR 						STRING
	, REGISTER_DATE 				STRING
	, REQUEST_TIME 					STRING
	, LOAN_TYPE 					STRING
	, LOAN_STATUS 					STRING
	, LAST_LOAN_STATUS 				STRING
	, LOAN_INIT_TERM 				INT
	, CURR_TERM 					INT
	, REMAIN_TERM 					INT
	, LOAN_INIT_PRIN 				DECIMAL(20, 6)
	, LOAN_FIXED_PMT_PRIN 			DECIMAL(20, 6)
	, LOAN_FIRST_TERM_PRIN 			DECIMAL(20, 6)
	, LOAN_FINAL_TERM_PRIN 			DECIMAL(20, 6)
	, LOAN_INIT_FEE 				DECIMAL(20, 6)
	, LOAN_FIXED_FEE 				DECIMAL(20, 6)
	, LOAN_FIRST_TERM_FEE 			DECIMAL(20, 6)
	, LOAN_FINAL_TERM_FEE 			DECIMAL(20, 6)
	, UNSTMT_PRIN 					DECIMAL(20, 6)
	, UNSTMT_FEE 					DECIMAL(20, 6)
	, ACTIVE_DATE 					STRING
	, PAID_OUT_DATE 				STRING
	, TERMINAL_DATE 				STRING
	, TERMINAL_REASON_CD 			STRING
	, PAID_PRINCIPAL 				DECIMAL(20, 6)
	, PAID_INTEREST 				DECIMAL(20, 6)
	, PAID_FEE 						DECIMAL(20, 6)
	, LOAN_CURR_BAL 				DECIMAL(20, 6)
	, LOAN_BAL_XFROUT 				DECIMAL(20, 6)
	, LOAN_BAL_XFRIN 				DECIMAL(20, 6)
	, LOAN_PRIN_XFROUT 				DECIMAL(20, 6)
	, LOAN_PRIN_XFRIN 				DECIMAL(20, 6)
	, LOAN_FEE_XFROUT 				DECIMAL(20, 6)
	, LOAN_FEE_XFRIN 				DECIMAL(20, 6)
	, ORIG_TXN_AMT 					DECIMAL(20, 6)
	, ORIG_TRANS_DATE 				STRING
	, ORIG_AUTH_CODE 				STRING
	, LOAN_CODE 					STRING
	, REGISTER_ID 					INT
	, EXTEND_INIT_PRIN 				DECIMAL(20, 6)
	, EXTEND_DATE 					STRING
	, BEF_EXTEND_FIXED_PMT_PRIN 	DECIMAL(20, 6)
	, BEF_EXTEND_INIT_TERM 			INT
	, BEF_EXTEND_FIRST_TERM_PRIN	DECIMAL(20, 6)
	, BEF_EXTEND_FINAL_TERM_PRIN 	DECIMAL(20, 6)
	, BEF_EXTEND_INIT_FEE 			DECIMAL(20, 6)
	, BEF_EXTEND_FIXED_FEE 			DECIMAL(20, 6)
	, BEF_EXTEND_FIRST_TERM_FEE 	DECIMAL(20, 6)
	, BEF_EXTEND_FINAL_TERM_FEE 	DECIMAL(20, 6)
	, EXTEND_FIRST_TERM_FEE 		DECIMAL(20, 6)
	, LOAN_FEE_METHOD 				STRING
	, INTEREST_RATE 				DECIMAL(20, 6)
	, PENALTY_RATE 					DECIMAL(20, 6)
	, COMPOUND_RATE 				DECIMAL(20, 6)
	, FLOAT_RATE 					DECIMAL(20, 6)
	, LOAN_EXPIRE_DATE 				STRING
	, LOAN_AGE_CODE 				STRING
	, PAYMENT_HST 					STRING
	, CTD_REPAY_AMT 				DECIMAL(20, 6)
	, PAST_EXTEND_CNT 				INT
	, PAST_SHORTEN_CNT 				INT
	, ADV_PMT_AMT 					DECIMAL(20, 6)
	, LAST_ACTION_DATE 				STRING
	, LAST_ACTION_TYPE 				STRING
	, CONTR_NBR 					STRING
	, GUARANTY_ID 					STRING
	, STAMPDUTY_AMT 				DECIMAL(20, 6)
	, UNSTMT_STAMPDUTY_AMT 			DECIMAL(20, 6)
	, LOAN_STAMPDUTY_AMT 			DECIMAL(20, 6)
	, PAID_STAMPDUTY_AMT 			DECIMAL(20, 6)
	, TOT_LIFE_INSU_AMT 			DECIMAL(20, 6)
	, UNSTMT_LIFE_INSU_AMT 			DECIMAL(20, 6)
	, PAST_LIFE_INSU_AMT 			DECIMAL(20, 6)
	, PAID_LIFE_INSU_AMT 			DECIMAL(20, 6)
	, LIFE_INSU_FEE_RATE 			DECIMAL(20, 6)
	, STAMPDUTY_RATE 				DECIMAL(20, 6)
	, INSURANCE_RATE 				DECIMAL(20, 6)
	, OVERDUE_DATE 					STRING
	, LAST_PENALTY_DATE 			STRING
	, INSURANCE_AMT 				DECIMAL(20, 6)
	, UNSTMT_INSURANCE_AMT 			DECIMAL(20, 6)
	, LOAN_INSURANCE_AMT 			DECIMAL(20, 6)
	, PAID_INSURANCE_AMT 			DECIMAL(20, 6)
	, LOAN_INS_FEE_METHOD 			STRING
	, STAMPDUTY_METHOD 				STRING
	, LIFE_INSU_FEE_METHOD 			STRING
	, CREATE_TIME 					STRING
	, CREATE_USER 					STRING
	, LST_UPD_TIME 					STRING
	, LST_UPD_USER 					STRING
	, MAX_CPD 						INT
	, MAX_CPD_DATE 					STRING
	, MAX_DPD 						INT
	, MAX_DPD_DATE 					STRING
	, STAMP_CUSTOM_IND 				STRING
	, IS_OFFSET_RATE 				STRING
	, CPD_BEGIN_DATE 				STRING
	, TOT_PREPAY_PKG_AMT 			DECIMAL(20, 6)
	, UNSTMT_PREPAY_PKG_AMT 		DECIMAL(20, 6)
	, PAST_PREPAY_PKG_AMT 			DECIMAL(20, 6)
	, PAID_PREPAY_PKG_AMT 			DECIMAL(20, 6)
	, PREPAY_PKG_FEE_RATE 			DECIMAL(20, 6)
	, PREPAY_PKG_FEE_METHOD 		STRING
	, LOAN_FEE_DEF_ID 				STRING
	, AGREEMENT_RATE_IND 			STRING
	, FEE_RATE 						DECIMAL(20, 6)
	, FEE_AMT 						DECIMAL(20, 6)
	, LIFE_INSU_FEE_AMT 			DECIMAL(20, 6)
	, INS_AMT 						DECIMAL(20, 6)
	, INSTALLMENT_FEE_RATE 			DECIMAL(20, 6)
	, INSTALLMENT_FEE_AMT 			DECIMAL(20, 6)
	, PREPAY_PKG_FEE_AMT 			DECIMAL(20, 6)
	, STAMP_AMT 					DECIMAL(20, 6)
	, JOIN_LIFE_INSU_IND 			STRING
	, SVCFEE_METHOD 				STRING
	, TOL_SVC_FEE 					DECIMAL(20, 6)
	, UNSTMT_SVC_FEE 				DECIMAL(20, 6)
	, PAST_SVC_FEE 					DECIMAL(20, 6)
	, PAID_SVC_FEE 					DECIMAL(20, 6)
	, REPLACE_SVC_FEE_RATE 			DECIMAL(20, 6)
	, REPLACE_SVC_FEE_AMT 			DECIMAL(20, 6)
	, REPLACE_SVC_FEE_METHOD 		STRING
	, TOT_REPLACE_SVC_FEE 			DECIMAL(20, 6)
	, UNSTMT_REPLACE_SVC_FEE 		DECIMAL(20, 6)
	, PAST_REPLACE_SVC_FEE 			DECIMAL(20, 6)
	, PAID_REPLACE_SVC_FEE 			DECIMAL(20, 6)
	, PREMIUM_AMT 					DECIMAL(20, 6)
	, PREMIUM_IND 					STRING
	, REPLACE_PENALTY_RATE 			DECIMAL(20, 6)
	, PREPAY_PKG_IND 				STRING
	, APPLY_TERM 					INT
	, APPLY_DELAY_TERM 				INT
	, ACCU_APPLY_COUNT 				INT
	, ACCU_DELAY_COUNT 				INT
	, PAY_DATE_TERM 				INT
	, PAY_DATE_BEG_DATE 			STRING
	, PAY_DATE_ACCU 				INT
	, COMPENSATE_COUNT 				INT
	, COMPENSATE_AMT_SUM 			DECIMAL(20, 6)
	, COMPENSATE_REFUND_COUNT 		INT
	, COMPENSATE_REFUND_AMT_SUM 	DECIMAL(20, 6)
	, END_LOAN_TYPE 				STRING
	, CTD_SDPAY_AMT 				DECIMAL(20, 6)
	, PROD_OWNERSHIP 				STRING
	, BIGDATA_DEL_STATUS			INT
	, BIGDATA_SYNC_TIME				BIGINT
	, PRIMARY KEY(LOAN_ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.ccs_loan_reg(
	REGISTER_ID 				INT
	, ORG 						STRING
	, ACCT_NBR 					BIGINT
	, ACCT_TYPE 				STRING
	, REGISTER_DATE 			STRING
	, REQUEST_TIME 				STRING
	, LOGIC_CARD_NBR 			STRING
	, CARD_NBR 					STRING
	, REF_NBR 					STRING
	, LOAN_TYPE 				STRING
	, LOAN_REG_STATUS 			STRING
	, LOAN_INIT_TERM 			INT
	, LOAN_INIT_PRIN 			DECIMAL(20, 6)
	, LOAN_FIXED_PMT_PRIN 		DECIMAL(20, 6)
	, LOAN_FIRST_TERM_PRIN 		DECIMAL(20, 6)
	, LOAN_FINAL_TERM_PRIN 		DECIMAL(20, 6)
	, LOAN_INIT_FEE 			DECIMAL(20, 6)
	, LOAN_FIXED_FEE 			DECIMAL(20, 6)
	, LOAN_FIRST_TERM_FEE 		DECIMAL(20, 6)
	, LOAN_FINAL_TERM_FEE 		DECIMAL(20, 6)
	, LOAN_FEE_METHOD 			STRING
	, ORIG_TXN_AMT 				DECIMAL(20, 6)
	, ORIG_TRANS_DATE 			STRING
	, ORIG_AUTH_CODE 			STRING
	, LOAN_CODE 				STRING
	, B007_TXN_TIME 			STRING
	, B011_TRACE 				STRING
	, B032_ACQ_INST 			STRING
	, B033_FWD_INS 				STRING
	, LOAN_ACTION 				STRING
	, LOAN_SVC_FEE 				DECIMAL(20, 6)
	, REMARK 					STRING
	, MATCHED 					STRING
	, INTEREST_RATE 			DECIMAL(20, 6)
	, PENALTY_RATE 				DECIMAL(20, 6)
	, COMPOUND_RATE 			DECIMAL(20, 6)
	, FLOAT_RATE 				DECIMAL(20, 6)
	, ADV_PMT_AMT 				DECIMAL(20, 6)
	, DUE_BILL_NO 				STRING
	, VALID_DATE 				STRING
	, EXTEND_TERM 				INT
	, SHORTED_TYPE 				STRING
	, SHORTED_TERM 				INT
	, SHORTED_PMT_DUE 			DECIMAL(20, 6)
	, LOAN_SVC_FEE_RETURN 		DECIMAL(20, 6)
	, CONTR_NBR 				STRING
	, GUARANTY_ID 				STRING
	, PRE_AD_DATE 				STRING
	, PRE_AD_AMT 				DECIMAL(20, 6)
	, DD_RSP_FLAG 				STRING
	, INSURANCE_RATE 			DECIMAL(20, 6)
	, AD_DEBIT_AMT 				DECIMAL(20, 6)
	, STAMPDUTY_RATE 			DECIMAL(20, 6)
	, STAMPDUTY_AMT 			DECIMAL(20, 6)
	, LIFE_INSU_FEE_RATE 		DECIMAL(20, 6)
	, TOT_LIFE_INSU_AMT 		DECIMAL(20, 6)
	, LOAN_INS_FEE_METHOD 		STRING
	, LIFE_INSU_FEE_METHOD 		STRING
	, STAMPDUTY_METHOD 			STRING
	, INSURANCE_AMT 			DECIMAL(20, 6)
	, CREATE_TIME 				STRING
	, CREATE_USER 				STRING
	, LST_UPD_TIME 				STRING
	, LST_UPD_USER 				STRING
	, PREPAY_PKG_FEE_RATE 		DECIMAL(20, 6)
	, TOT_PREPAY_PKG_AMT 		DECIMAL(20, 6)
	, PREPAY_PKG_FEE_METHOD 	STRING
	, JOIN_LIFE_INSU_IND 		STRING
	, JOIN_PREPAY_PKG_IND 		STRING
	, LOAN_FEE_DEF_ID 			STRING
	, AGREEMENT_RATE_IND 		STRING
	, FEE_AMT 					DECIMAL(20, 6)
	, LIFE_INSU_FEE_AMT 		DECIMAL(20, 6)
	, FEE_RATE 					DECIMAL(20, 6)
	, INS_AMT 					DECIMAL(20, 6)
	, INSTALLMENT_FEE_RATE 		DECIMAL(20, 6)
	, INSTALLMENT_FEE_AMT 		DECIMAL(20, 6)
	, PREPAY_PKG_FEE_AMT 		DECIMAL(20, 6)
	, STAMP_AMT 				DECIMAL(20, 6)
	, SVCFEE_METHOD 			STRING
	, TOL_SVC_FEE 				DECIMAL(20, 6)
	, REPLACE_SVC_FEE_RATE 		DECIMAL(20, 6)
	, REPLACE_SVC_FEE_AMT 		DECIMAL(20, 6)
	, REPLACE_SVC_FEE_METHOD	STRING
	, TOT_REPLACE_SVC_FEE 		DECIMAL(20, 6)
	, PREMIUM_AMT 				DECIMAL(20, 6)
	, PREMIUM_IND 				STRING
	, REPLACE_PENALTY_RATE 		DECIMAL(20, 6)
	, PREPAY_PKG_IND 			STRING
	, APPLY_TERM 				INT
	, APPLY_DELAY_TERM 			INT
	, PAY_DATE_TERM 			INT
	, PAY_DATE_BEG_DATE 		STRING
	, PAY_DATE_ACCU 			INT
	, PAY_DATE_ORIGIN 			INT
	, PAY_DATE_AFTER 			INT
	, PROD_OWNERSHIP 			STRING
	, REMAIN_PRIN 				DECIMAL(20, 6)
	, BIGDATA_DEL_STATUS		INT
	, BIGDATA_SYNC_TIME			BIGINT
	, PRIMARY KEY(REGISTER_ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.ccs_loan_reg_hst(
	REGISTER_ID 				INT
	, ORG 						STRING
	, ACCT_NBR 					BIGINT
	, ACCT_TYPE 				STRING
	, REGISTER_DATE 			STRING
	, REQUEST_TIME 				STRING
	, LOGIC_CARD_NBR 			STRING
	, CARD_NBR 					STRING
	, REF_NBR 					STRING
	, LOAN_TYPE 				STRING
	, LOAN_REG_STATUS 			STRING
	, LOAN_INIT_TERM 			INT
	, LOAN_INIT_PRIN 			DECIMAL(20, 6)
	, LOAN_FIXED_PMT_PRIN 		DECIMAL(20, 6)
	, LOAN_FIRST_TERM_PRIN 		DECIMAL(20, 6)
	, LOAN_FINAL_TERM_PRIN 		DECIMAL(20, 6)
	, LOAN_INIT_FEE 			DECIMAL(20, 6)
	, LOAN_FIXED_FEE 			DECIMAL(20, 6)
	, LOAN_FIRST_TERM_FEE 		DECIMAL(20, 6)
	, LOAN_FINAL_TERM_FEE 		DECIMAL(20, 6)
	, LOAN_FEE_METHOD 			STRING
	, ORIG_TXN_AMT 				DECIMAL(20, 6)
	, ORIG_TRANS_DATE 			STRING
	, ORIG_AUTH_CODE 			STRING
	, LOAN_CODE 				STRING
	, B007_TXN_TIME 			STRING
	, B011_TRACE 				STRING
	, B032_ACQ_INST 			STRING
	, B033_FWD_INS 				STRING
	, LOAN_ACTION 				STRING
	, LOAN_SVC_FEE_RETURN 		DECIMAL(20, 6)
	, LOAN_SVC_FEE 				DECIMAL(20, 6)
	, REMARK 					STRING
	, MATCHED 					STRING
	, INTEREST_RATE 			DECIMAL(20, 6)
	, PENALTY_RATE 				DECIMAL(20, 6)
	, COMPOUND_RATE 			DECIMAL(20, 6)
	, FLOAT_RATE 				DECIMAL(20, 6)
	, ADV_PMT_AMT 				DECIMAL(20, 6)
	, DUE_BILL_NO 				STRING
	, VALID_DATE 				STRING
	, BEF_EXTEND_INIT_TERM 		INT
	, BEF_EXTEND_INIT_PRIN 		DECIMAL(20, 6)
	, EXTEND_TERM 				INT
	, BEF_SHORTEN_INIT_TERM 	INT
	, BEF_SHORTEN_INIT_PRIN 	DECIMAL(20, 6)
	, SHORTED_TYPE 				STRING
	, SHORTED_TERM 				INT
	, SHORTED_PMT_DUE 			DECIMAL(20, 6)
	, CONTR_NBR 				STRING
	, GUARANTY_ID 				STRING
	, PRE_AD_DATE 				STRING
	, PRE_AD_AMT 				DECIMAL(20, 6)
	, DD_RSP_FLAG 				STRING
	, INSURANCE_RATE 			DECIMAL(20, 6)
	, AD_DEBIT_AMT 				DECIMAL(20, 6)
	, STAMPDUTY_AMT 			DECIMAL(20, 6)
	, STAMPDUTY_RATE 			DECIMAL(20, 6)
	, TOT_LIFE_INSU_AMT 		DECIMAL(20, 6)
	, LIFE_INSU_FEE_RATE 		DECIMAL(20, 6)
	, LIFE_INSU_FEE_METHOD 		STRING
	, STAMPDUTY_METHOD 			STRING
	, LOAN_INS_FEE_METHOD 		STRING
	, INSURANCE_AMT 			DECIMAL(20, 6)
	, CREATE_TIME 				STRING
	, CREATE_USER 				STRING
	, LST_UPD_TIME 				STRING
	, LST_UPD_USER 				STRING
	, TOT_PREPAY_PKG_AMT 		DECIMAL(20, 6)
	, PREPAY_PKG_FEE_RATE 		DECIMAL(20, 6)
	, PREPAY_PKG_FEE_METHOD 	STRING
	, JOIN_LIFE_INSU_IND 		STRING
	, JOIN_PREPAY_PKG_IND 		STRING
	, LOAN_FEE_DEF_ID 			STRING
	, AGREEMENT_RATE_IND 		STRING
	, FEE_AMT 					DECIMAL(20, 6)
	, LIFE_INSU_FEE_AMT 		DECIMAL(20, 6)
	, FEE_RATE 					DECIMAL(20, 6)
	, INS_AMT 					DECIMAL(20, 6)
	, INSTALLMENT_FEE_RATE 		DECIMAL(20, 6)
	, INSTALLMENT_FEE_AMT 		DECIMAL(20, 6)
	, PREPAY_PKG_FEE_AMT 		DECIMAL(20, 6)
	, STAMP_AMT 				DECIMAL(20, 6)
	, SVCFEE_METHOD 			STRING
	, REPLACE_SVC_FEE_METHOD 	STRING
	, REPLACE_SVC_FEE_RATE 		DECIMAL(20, 6)
	, REPLACE_SVC_FEE_AMT 		DECIMAL(20, 6)
	, TOT_REPLACE_SVC_FEE 		DECIMAL(20, 6)
	, PREMIUM_AMT 				DECIMAL(20, 6)
	, PREMIUM_IND 				STRING
	, REPLACE_PENALTY_RATE 		DECIMAL(20, 6)
	, PREPAY_PKG_IND 			STRING
	, APPLY_DELAY_TERM 			INT
	, APPLY_TERM 				INT
	, PAY_DATE_TERM 			INT
	, PAY_DATE_BEG_DATE 		STRING
	, PAY_DATE_ACCU 			INT
	, PAY_DATE_ORIGIN 			INT
	, PAY_DATE_AFTER 			INT
	, PROD_OWNERSHIP 			STRING
	, REMAIN_PRIN 				DECIMAL(20, 6)
	, BIGDATA_DEL_STATUS		INT
	, BIGDATA_SYNC_TIME			BIGINT
	, PRIMARY KEY(REGISTER_ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.ccs_acct(
	ACCT_NBR 						BIGINT
	, ACCT_TYPE 					STRING
	, ORG							STRING 
	, CUST_ID 						INT
	, CUST_LMT_ID 					INT
	, PRODUCT_CD 					STRING
	, DEFAULT_LOGIC_CARD_NBR 		STRING  COMMENT '取自默认卡产品的主卡卡号，用于作为滞纳金、超限费的入账卡号'
	, CURRENCY 						STRING
	, CREDIT_LMT 					DECIMAL(20, 6)
	, TEMP_LMT 						DECIMAL(20, 6)
	, TEMP_LMT_BEG_DATE 			STRING
	, TEMP_LMT_END_DATE 			STRING
	, CASH_LMT_RATE 				DECIMAL(20, 6)  COMMENT '取现额度比例（占用账户信用额度）'
	, OVRLMT_RATE 					DECIMAL(20, 6)  COMMENT '授权允许的超限比例，来自账户下最高级别卡产品的参数定义。'
	, LOAN_LMT_RATE 				DECIMAL(20, 6)  COMMENT '额度内分期额度比例'
	, CURR_BAL 						DECIMAL(20, 6)  COMMENT '当前欠款（负值表示有溢缴款）'
	, CASH_BAL 						DECIMAL(20, 6)
	, PRINCIPAL_BAL 				DECIMAL(20, 6)  COMMENT '当前本金余额'
	, LOAN_BAL 						DECIMAL(20, 6)  COMMENT '当前额度内分期余额'
	, DISPUTE_AMT 					DECIMAL(20, 6)  COMMENT '当前争议金额'
	, BEG_BAL 						DECIMAL(20, 6)
	, PMT_DUE_DAY_BAL 				DECIMAL(20, 6)  COMMENT '到期还款日余额'
	, QUAL_GRACE_BAL 				DECIMAL(20, 6)  COMMENT '持卡人还清该欠款，则会对账户进行全额还款免息，该金额会显示在账单上，小于等于账户账单余额'
	, GRACE_DAYS_FULL_IND 			STRING
	, POINTS_BEG_BAL 				DECIMAL(20, 6)
	, CTD_POINTS 					DECIMAL(20, 6)
	, CTD_SPEND_POINTS 				DECIMAL(20, 6)
	, CTD_ADJ_POINTS 				DECIMAL(20, 6)
	, POINTS_BAL 					DECIMAL(20, 6)
	, SETUP_DATE 					STRING
	, DORMENT_DATE 					STRING  COMMENT '账户睡眠日期'
	, EACTIVE_DATE 					STRING  COMMENT '账户恢复活动日期'
	, OVRLMT_DATE 					STRING  COMMENT '超限日期'
	, OVRLMT_NBR_OF_CYC 			INT  COMMENT '连续超限账期'
	, NAME 							STRING  COMMENT '客户姓名 - 冗余字段，从客户表复制过来，这样批量处理时可以不用关联客户信息'
	, GENDER 						STRING  COMMENT 'M|男\NF|女'
	, OWNING_BRANCH 				STRING
	, MOBILE_NO 					STRING
	, CORP_NAME 					STRING
	, CYCLE_DAY 					STRING  COMMENT '账户的账单日期'
	, STMT_FLAG 					STRING  COMMENT '标识账户是否出账单，及出联机账单还是实体账单\NY|要求出账单\NN|不输出账单'
	, STMT_MAIL_ADDR_IND 			STRING
	, STMT_MEDIA_TYPE 				STRING  COMMENT 'P|纸质账单\NE|电子账单\NM|彩信账单\NB|BOTH\N'
	, STMT_COUNTRY_CODE 			STRING  COMMENT '账单地址国家代码（从客户信息复制过来，保证核心快速处理）'
	, STMT_STATE 					STRING  COMMENT '账单地址省份'
	, STMT_CITY 					STRING  COMMENT '账单地址城市'
	, STMT_DISTRICT 				STRING  COMMENT '账单地址行政区'
	, STMT_ADDRESS					STRING  COMMENT '账单地址'
	, STMT_POSTCODE 				STRING  COMMENT '账单地址邮政编码'
	, EMAIL 						STRING
	, BLOCK_CODE 					STRING
	, AGE_CODE 						STRING  COMMENT '实体账单不需要显示此域（但可以用作账单拖欠信息提醒）， 联机账单需要'
	, AGE_CODE_GL 					STRING
	, MEMO_DB 						DECIMAL(20, 6)
	, MEMO_CASH 					DECIMAL(20, 6)
	, MEMO_CR 						DECIMAL(20, 6)
	, DD_IND 						STRING  COMMENT 'M|最小额扣款\NF|全额扣款\NC|最小额储蓄购汇\NE|全额储蓄购汇\N'
	, DD_BANK_NAME 					STRING  COMMENT '约定还款扣款账户银行名称'
	, DD_BANK_BRANCH 				STRING
	, DD_BANK_ACCT_NBR 				STRING  COMMENT '约定还款扣款账号'
	, DD_BANK_ACCT_NAME 			STRING  COMMENT '约定还款扣款账户姓名'
	, LAST_DD_AMT 					DECIMAL(20, 6)  COMMENT '上期约定还款金额'
	, LAST_DD_DATE 					STRING  COMMENT '上期约定还款日期'
	, DUAL_BILLING_FLAG 			STRING  COMMENT '取值为M,F时账单系统需要将本外币账单接口合并生成实体账单\NN|不还款\NM|最小额还款\NF|全额还款\N'
	, LAST_PMT_AMT 					DECIMAL(20, 6)  COMMENT '上笔还款金额'
	, LAST_PMT_DATE 				STRING
	, LAST_STMT_DATE 				STRING  COMMENT '上个账单日'
	, LAST_PMT_DUE_DATE 			STRING  COMMENT '上个到期还款日'
	, LAST_AGING_DATE 				STRING  COMMENT '上次账龄提升日，可以用来代替DELQ DAYS的计算'
	, COLLECT_IN_DATE 				STRING  COMMENT '进入催收日期'
	, COLLECT_OUT_DATE 				STRING  COMMENT '出催收队列时间'
	, NEXT_STMT_DATE 				STRING  COMMENT '下个账单日'
	, PMT_DUE_DATE 					STRING
	, DD_DATE 						STRING  COMMENT '约定还款扣款文件生成日期'
	, GRACE_DATE 					STRING  COMMENT '宽限日'
	, DUAL_BILLING_DATE 			STRING  COMMENT '本币还外币日期'
	, FIRST_STMT_DATE 				STRING  COMMENT '首个账单日'
	, CHARGE_OFF_DATE 				STRING  COMMENT '转呆账日期'
	, CLOSE_DATE  					STRING  COMMENT '卡片账户置上待销卡销户锁定码的日期\N在销卡时置上销卡日期，在销卡撤销时清零销卡日期'
	, CLOSED_DATE 					STRING  COMMENT '最终销户日期，指账户CLOSED'
	, FIRST_RETL_DATE 				STRING  COMMENT '首次消费日期，无消费是该字段为NULL'
	, FIRST_RETL_AMT 				DECIMAL(20, 6)  COMMENT '首次消费金额，无消费是该字段为NULL'
	, TOT_DUE_AMT   				DECIMAL(20, 6)
	, CURR_DUE_AMT  				DECIMAL(20, 6)
	, PAST_DUE_AMT1 				DECIMAL(20, 6)  COMMENT '上个月最小还款额'
	, PAST_DUE_AMT2 				DECIMAL(20, 6)  COMMENT '上2个月最小还款额'
	, PAST_DUE_AMT3 				DECIMAL(20, 6)  COMMENT '上3个月最小还款额'
	, PAST_DUE_AMT4 				DECIMAL(20, 6)  COMMENT '上4个月最小还款额'
	, PAST_DUE_AMT5 				DECIMAL(20, 6)  COMMENT '上5个月最小还款额'
	, PAST_DUE_AMT6 				DECIMAL(20, 6)  COMMENT '上6个月最小还款额'
	, PAST_DUE_AMT7 				DECIMAL(20, 6)  COMMENT '上7个月最小还款额'
	, PAST_DUE_AMT8 				DECIMAL(20, 6)  COMMENT '上8个月最小还款额'
	, CTD_CASH_AMT					DECIMAL(20, 6)
	, CTD_CASH_CNT					INT COMMENT '本账期取现笔数'
	, CTD_RETAIL_AMT 				DECIMAL(20, 6)  COMMENT '本账期联机借记金额累计值，在授权时维护，批量不参与'
	, CTD_RETAIL_CNT 				INT COMMENT '本账期消费笔数'
	, CTD_REPAY_AMT  				DECIMAL(20, 6)  COMMENT '本账期还款金额'
	, CTD_REPAY_CNT  				INT COMMENT '本账期还款笔数'
	, CTD_DB_ADJ_AMT 				DECIMAL(20, 6)  COMMENT '本账期借记调整金额'
	, CTD_DB_ADJ_CNT 				INT COMMENT '本账期借记调整笔数'
	, CTD_CR_ADJ_AMT 				DECIMAL(20, 6)  COMMENT '本账期贷记调整金额'
	, CTD_CR_ADJ_CNT 				INT COMMENT '本账期贷记调整笔数'
	, CTD_FEE_AMT 					DECIMAL(20, 6)  COMMENT '本账期费用金额'
	, CTD_FEE_CNT 					INT COMMENT '本账期费用笔数'
	, CTD_INTEREST_AMT 				DECIMAL(20, 6)
	, CTD_INTEREST_CNT 				INT
	, CTD_REFUND_AMT 				DECIMAL(20, 6) COMMENT '本账期退货金额'
	, CTD_REFUND_CNT 				INT COMMENT '本账期退货笔数'
	, CTD_MAX_OVRLMT_AMT 			DECIMAL(20, 6)
	, MTD_RETAIL_AMT 				DECIMAL(20, 6)
	, MTD_RETAIL_CNT 				INT COMMENT '本月消费笔数'
	, MTD_CASH_AMT 					DECIMAL(20, 6)
	, MTD_CASH_CNT 					INT COMMENT '本月取现笔数'
	, MTD_REFUND_AMT 				DECIMAL(20, 6)
	, MTD_REFUND_CNT 				INT COMMENT '本月退货笔数'
	, YTD_RETAIL_AMT 				DECIMAL(20, 6)
	, YTD_RETAIL_CNT 				INT COMMENT '本年消费笔数'
	, YTD_CASH_AMT 					DECIMAL(20, 6)  COMMENT '本年取现金额'
	, YTD_CASH_CNT 					INT COMMENT '本年取现次数'
	, YTD_REFUND_AMT 				DECIMAL(20, 6)  COMMENT '本年退货金额'
	, YTD_REFUND_CNT 				INT COMMENT '本年退货次数'
	, YTD_OVRLMT_FEE_AMT 			DECIMAL(20, 6)
	, YTD_OVRLMT_FEE_CNT 			INT
	, YTD_LATE_FEE_AMT 				DECIMAL(20, 6)
	, YTD_LATE_FEE_CNT 				INT
	, LTD_RETAIL_AMT 				DECIMAL(20, 6)
	, LTD_RETAIL_CNT 				INT COMMENT '历史消费次数'
	, LTD_CASH_AMT 					DECIMAL(20, 6)
	, LTD_CASH_CNT 					INT
	, LTD_REFUND_AMT 				DECIMAL(20, 6) COMMENT '历史退货金额'
	, LTD_REFUND_CNT 				INT COMMENT '历史退货次数'
	, LTD_HIGHEST_PRIN 				DECIMAL(20, 6) COMMENT '历史最高本金欠款'
	, LTD_HIGHEST_CR_BAL 			DECIMAL(20, 6) COMMENT '历史最高溢缴款'
	, LTD_HIGHEST_BAL 				DECIMAL(20, 6) COMMENT '历史最高欠款'
	, COLLECT_CNT 					INT COMMENT '进入催收队列次数'
	, COLLECTOR 					STRING COMMENT '催收系统分配的催收员代码'
	, COLLECT_REASON 				STRING COMMENT 'B0|锁定码催收，优先级第1\NA0|首次还款拖欠催收，优先级第2\NA1|账龄拖欠催收，优先级第3\NO0|超限催收，优先级第4\N'
	, AGE_HST 						STRING COMMENT '过去24个账单周期的账龄，取值范围为0-9'
	, PAYMENT_HST 					STRING COMMENT '‎记录过去24个月的还款历史，每个字节的含义如下：B|全额还款\ND|部分还款\NU|还款未达最小还款额\NN|未还款\NC|无需还款'
	, WAIVE_OVLFEE_IND  			STRING
	, WAIVE_CARDFEE_IND 			STRING COMMENT '账户上的卡年费免除标志对其下所有卡生，卡片上的仅对本卡生效'
	, WAIVE_LATEFEE_IND 			STRING
	, WAIVE_SVCFEE_IND  			STRING
	, USER_CODE1 					STRING
	, USER_CODE2 					STRING
	, USER_CODE3 					STRING
	, USER_CODE4 					STRING
	, USER_CODE5 					STRING
	, USER_CODE6 					STRING
	, USER_DATE1 					STRING
	, USER_DATE2 					STRING
	, USER_DATE3 					STRING
	, USER_DATE4 					STRING
	, USER_DATE5 					STRING
	, USER_DATE6 					STRING
	, USER_NUMBER1 					INT
	, USER_NUMBER2 					INT
	, USER_NUMBER3 					INT
	, USER_NUMBER4 					INT
	, USER_NUMBER5 					INT
	, USER_NUMBER6 					INT
	, USER_FIELD1 					STRING
	, USER_FIELD2 					STRING
	, USER_FIELD3 					STRING
	, USER_FIELD4 					STRING
	, USER_FIELD5 					STRING
	, USER_FIELD6 					STRING
	, USER_AMT1 					DECIMAL(20, 6)
	, USER_AMT2 					DECIMAL(20, 6)
	, USER_AMT3 					DECIMAL(20, 6)
	, USER_AMT4 					DECIMAL(20, 6)
	, USER_AMT5 					DECIMAL(20, 6)
	, USER_AMT6 					DECIMAL(20, 6)
	, MTD_PAYMENT_AMT 				DECIMAL(20, 6)
	, MTD_PAYMENT_CNT 				INT
	, YTD_REPAY_AMT 				DECIMAL(20, 6)
	, YTD_REPAY_CNT 				INT
	, LTD_REPAY_AMT 				DECIMAL(20, 6)
	, LTD_REPAY_CNT 				INT
	, SMS_IND 						STRING
	, USER_SMS_AMT 					DECIMAL(20, 6)
	, YTD_CYCLE_CHAG_CNT 			INT
	, LAST_POST_DATE 				STRING
	, CONTR_NBR   					STRING
	, GUARANTY_ID 					STRING
	, DD_BANK_PROVINCE 				STRING
	, DD_BANK_PROVINCE_CODE 		STRING
	, DD_BANK_CITY 					STRING
	, DD_BANK_CITY_CODE 			STRING
	, CUST_SOURCE 					STRING
	, CREATE_TIME 					STRING
	, CREATE_USER 					STRING
	, LST_UPD_TIME 					STRING
	, LST_UPD_USER 					STRING
	, AGREEMENT_RATE_EXPIRE_DATE	STRING
	, ACCT_EXPIRE_DATE 				STRING
	, APPLICATION_NO 				STRING
	, LTD_LOAN_AMT 					DECIMAL(20, 6)
	, LOAN_MOLD 					STRING
	, ACQ_ID 						STRING
	, LAST_SYNC_DATE 				STRING
	, AGREEMENT_RATE_IND 			STRING
	, FEE_RATE 						DECIMAL(20, 6)
	, FEE_AMT  						DECIMAL(20, 6)
	, LIFE_INSU_FEE_RATE 			DECIMAL(20, 6)
	, LIFE_INSU_FEE_AMT 			DECIMAL(20, 6)
	, INSURANCE_RATE 				DECIMAL(20, 6)
	, INS_AMT 						DECIMAL(20, 6)
	, INSTALLMENT_FEE_RATE 			DECIMAL(20, 6)
	, INSTALLMENT_FEE_AMT 			DECIMAL(20, 6)
	, PREPAY_PKG_FEE_RATE 			DECIMAL(20, 6)
	, PREPAY_PKG_FEE_AMT 			DECIMAL(20, 6)
	, PENALTY_RATE 					DECIMAL(20, 6)
	, COMPOUND_RATE 				DECIMAL(20, 6)
	, INTEREST_RATE 				DECIMAL(20, 6)
	, STAMP_AMT 					DECIMAL(20, 6)
	, STAMPDUTY_RATE 				DECIMAL(20, 6)
	, LAST_LIMIT_ADJ_DATE 			STRING  COMMENT '上次额度调整日期'
	, LOAN_CODE 					STRING
	, LOAN_FEE_DEF_ID 				STRING
	, APPLY_DATE 					STRING
	, PURPOSE 						STRING
	, SUB_TERMINAL_TYPE  			STRING
	, JOIN_LIFE_INSU_IND 			STRING
	, JOIN_PREPAY_PKG_IND 			STRING
	, REPLACE_SVC_FEE_RATE 			DECIMAL(20, 6)
	, REPLACE_SVC_FEE_AMT 			DECIMAL(20, 6)
	, REPLACE_PENALTY_RATE 			DECIMAL(20, 6)
	, PREPAY_PKG_IND 				STRING
	, OVER_LOAN_MARK 				STRING
	, IS_MERGE_BILL_DAY 			STRING
	, CT_BANK_ACCT_NAME 			STRING
	, CT_BANK_ACCT_NBR 				STRING
	, CT_BANK_NAME 					STRING
	, CT_BANK_BRANCH 				STRING
	, CT_BANK_PROVINCE 				STRING
	, CT_BANK_PROVINCE_CODE 		STRING
	, CT_BANK_CITY 					STRING
	, CT_BANK_CITY_CODE 			STRING
	, DD_BANK_ACCT_PHONE 			STRING
	, CT_BANK_ACCT_PHONE 			STRING
	, IS_PUBLIC_CT_ACCOUNT 			STRING
	, IS_PUBLIC_DD_ACCOUNT 			STRING
	, BIGDATA_DEL_STATUS			INT
	, BIGDATA_SYNC_TIME				BIGINT
	, PRIMARY KEY(ACCT_NBR,ACCT_TYPE)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.ccs_plan(
	PLAN_ID 					INT
	, ORG 						STRING
	, ACCT_NBR 					BIGINT
	, ACCT_TYPE 				STRING
	, LOGIC_CARD_NBR 			STRING 	COMMENT '主卡逻辑卡号'
	, PLAN_NBR 					STRING 		COMMENT '来自信用计划模板中的PLAN_ID，用来表示信用计划类型'
	, PLAN_TYPE 				STRING 		COMMENT '///\N@COM.SUNLINE.PPY.DICTIONARY.ENUMS.PLANTYPE'
	, PRODUCT_CD 				STRING
	, REF_NBR 					STRING 	COMMENT '内部交易参考号，生成规则：（YYMMDDHHMMDDSSS）+4位随机数+3位外部流水号末尾'
	, CURR_BAL 					DECIMAL(20, 6) 	COMMENT '当前欠款（负值表示有溢缴款）'
	, BEG_BAL 					DECIMAL(20, 6)
	, DISPUTE_AMT 				DECIMAL(20, 6) 	COMMENT '当前争议金额'
	, TOT_DUE_AMT 				DECIMAL(20, 6)
	, PLAN_ADD_DATE 			STRING
	, PAID_OUT_DATE 			STRING
	, PAST_PRINCIPAL 			DECIMAL(20, 6)
	, PAST_INTEREST 			DECIMAL(20, 6)
	, PAST_CARD_FEE 			DECIMAL(20, 6)
	, PAST_OVRLMT_FEE 			DECIMAL(20, 6)
	, PAST_LATE_FEE 			DECIMAL(20, 6)
	, PAST_NSFUND_FEE 			DECIMAL(20, 6) 	COMMENT '已出账单资金不足罚金（NONE SUFFICIENT FEE）'
	, PAST_TXN_FEE 				DECIMAL(20, 6) 	COMMENT '已出账单交易费'
	, PAST_SVC_FEE 				DECIMAL(20, 6) 	COMMENT '已出账单服务费'
	, PAST_INSURANCE 			DECIMAL(20, 6) 	COMMENT '已出账单保险金额'
	, PAST_USER_FEE1 			DECIMAL(20, 6) 	COMMENT '已出账单自定义费用1'
	, PAST_USER_FEE2 			DECIMAL(20, 6) 	COMMENT '已出账单自定义费用2'
	, PAST_USER_FEE3 			DECIMAL(20, 6) 	COMMENT '已出账单自定义费用3'
	, PAST_USER_FEE4 			DECIMAL(20, 6) 	COMMENT '已出账单自定义费用4'
	, PAST_USER_FEE5 			DECIMAL(20, 6) 	COMMENT '已出账单自定义费用5'
	, PAST_USER_FEE6 			DECIMAL(20, 6) 	COMMENT '已出账单自定义费用6'
	, CTD_PRINCIPAL 			DECIMAL(20, 6) 	COMMENT '本账期本金'
	, CTD_INTEREST 				DECIMAL(20, 6)
	, CTD_CARD_FEE 				DECIMAL(20, 6)
	, CTD_OVRLMT_FEE 			DECIMAL(20, 6)
	, CTD_LATE_FEE 				DECIMAL(20, 6)
	, CTD_NSFUND_FEE 			DECIMAL(20, 6) 	COMMENT '本账期资金不足罚金'
	, CTD_SVC_FEE 				DECIMAL(20, 6) 	COMMENT '本账期交易费'
	, CTD_TXN_FEE 				DECIMAL(20, 6) 	COMMENT '本账期服务费'
	, CTD_INSURANCE 			DECIMAL(20, 6) 	COMMENT '本账期保险金额'
	, CTD_USER_FEE1 			DECIMAL(20, 6)
	, CTD_USER_FEE2 			DECIMAL(20, 6) 	COMMENT '本账期新增自定义费用2'
	, CTD_USER_FEE3 			DECIMAL(20, 6) 	COMMENT '本账期新增自定义费用3'
	, CTD_USER_FEE4 			DECIMAL(20, 6) 	COMMENT '本账期新增自定义费4'
	, CTD_USER_FEE5 			DECIMAL(20, 6) 	COMMENT '本账期新增自定义费用5'
	, CTD_USER_FEE6 			DECIMAL(20, 6) 	COMMENT '本账期新增自定义费6'
	, CTD_AMT_DB 				DECIMAL(20, 6) 	COMMENT '当期借记金额，统计当期新增的借记交易金额'
	, CTD_AMT_CR 				DECIMAL(20, 6) 	COMMENT '当期贷记金额'
	, CTD_NBR_DB 				INT 			COMMENT '当期借记交易笔数'
	, CTD_NBR_CR 				INT 			COMMENT '当期贷记交易笔数'
	, NODEFBNP_INT_ACRU 		DECIMAL(20, 6) 	COMMENT '不享受免息期的交易已产生的未入账利息金额'
	, BEG_DEFBNP_INT_ACRU 		DECIMAL(20, 6) 	COMMENT '期初余额利息累计'
	, CTD_DEFBNP_INT_ACRU 		DECIMAL(20, 6) 	COMMENT '当期余额累计的利息'
	, USER_CODE1 				STRING
	, USER_CODE2 				STRING
	, USER_CODE3 				STRING
	, USER_CODE4 				STRING
	, USER_CODE5 				STRING
	, USER_CODE6 				STRING
	, USER_NUMBER1 				INT
	, USER_NUMBER2 				INT
	, USER_NUMBER3 				INT
	, USER_NUMBER4 				INT
	, USER_NUMBER5 				INT
	, USER_NUMBER6 				INT
	, USER_FIELD1 				STRING
	, USER_FIELD2 				STRING
	, USER_FIELD3 				STRING
	, USER_FIELD4 				STRING
	, USER_FIELD5 				STRING
	, USER_FIELD6 				STRING
	, USER_DATE1 				STRING
	, USER_DATE2 				STRING
	, USER_DATE3 				STRING
	, USER_DATE4 				STRING
	, USER_DATE5 				STRING
	, USER_DATE6 				STRING
	, USER_AMT1 				DECIMAL(20, 6)
	, USER_AMT2 				DECIMAL(20, 6)
	, USER_AMT3 				DECIMAL(20, 6)
	, USER_AMT4 				DECIMAL(20, 6)
	, USER_AMT5 				DECIMAL(20, 6)
	, USER_AMT6 				DECIMAL(20, 6)
	, PAST_PENALTY 				DECIMAL(20, 6)
	, CTD_PENALTY 				DECIMAL(20, 6)
	, PAST_COMPOUND 			DECIMAL(20, 6)
	, CTD_COMPOUND 				DECIMAL(20, 6)
	, PENALTY_ACRU 				DECIMAL(20, 6)
	, COMPOUND_ACRU 			DECIMAL(20, 6)
	, INTEREST_RATE 			DECIMAL(20, 6)
	, PENALTY_RATE 				DECIMAL(20, 6)
	, COMPOUND_RATE 			DECIMAL(20, 6)
	, USE_PLAN_RATE 			STRING 		COMMENT '///\N@COM.SUNLINE.PPY.DICTIONARY.ENUMS.INDICATOR'
	, LAST_PMT_DATE 			STRING
	, TERM 						INT
	, CTD_STAMPDUTY_AMT 		DECIMAL(20, 6)
	, PAST_STAMPDUTY_AMT 		DECIMAL(20, 6)
	, CTD_LIFE_INSU_AMT 		DECIMAL(20, 6)
	, PAST_LIFE_INSU_AMT 		DECIMAL(20, 6)
	, CTD_MULCT_AMT 			DECIMAL(20, 6)
	, PAST_MULCT_AMT 			DECIMAL(20, 6)
	, CREATE_TIME 				STRING
	, CREATE_USER 				STRING
	, LST_UPD_TIME 				STRING
	, LST_UPD_USER 				STRING
	, JPA_VERSION 				INT
	, CTD_PREPAY_PKG_FEE 		DECIMAL(20, 6)
	, PAST_PREPAY_PKG_FEE 		DECIMAL(20, 6)
	, ACCRU_PRIN_SUM 			DECIMAL(20, 6)
	, LAST_ACCRU_PRIN_SUM 		DECIMAL(20, 6)
	, CTD_REPLACE_SVC_FEE 		DECIMAL(20, 6)
	, PAST_REPLACE_SVC_FEE 		DECIMAL(20, 6)
	, REPLACE_PENALTY_RATE 		DECIMAL(20, 6)
	, CTD_REPLACE_PENALTY 		DECIMAL(20, 6)
	, PAST_REPLACE_PENALTY 		DECIMAL(20, 6)
	, REPLACE_PENALTY_ACRU 		DECIMAL(20, 6)
	, CTD_REPLACE_MULCT 		DECIMAL(20, 6)
	, PAST_REPLACE_MULCT 		DECIMAL(20, 6)
	, CTD_REPLACE_LATE_FEE 		DECIMAL(20, 6)
	, PAST_REPLACE_LATE_FEE 	DECIMAL(20, 6)
	, CTD_REPLACE_TXN_FEE 		DECIMAL(20, 6) 	COMMENT '未出账单代收交易费'
	, PAST_REPLACE_TXN_FEE 		DECIMAL(20, 6) 	COMMENT '已出账单代收交易费'
	, COMPENSATE_AMT 			DECIMAL(20, 6)
	, COMPENSATE_STATUS 		STRING 	COMMENT '///\N@COM.SUNLINE.CCS.PARAM.DEF.ENUMS.COMPENSATESTATUS'
	, GRACE_NODEFBNP_INT_ACRU 	DECIMAL(20, 6)
	, BIGDATA_DEL_STATUS		INT
	, BIGDATA_SYNC_TIME			BIGINT
	, PRIMARY KEY(PLAN_ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.ccs_customer(
	CUST_ID 		INT
	, ID_NO 		STRING
	, GENDER 		STRING
	, BIRTHDAY 		STRING
	, MOBILE_NO		STRING
	, BIGDATA_DEL_STATUS	INT
	, BIGDATA_SYNC_TIME		BIGINT
	, PRIMARY KEY(CUST_ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.ccs_order(
	ORDER_ID 				INT
	, ORG					STRING
	, CHANNEL_ID 			STRING
	, LOG_KV 				INT
	, ACCT_NBR 				BIGINT
	, ACCT_TYPE 			STRING
	, COMMAND_TYPE 			STRING
	, ORDER_BRIEF 			STRING
	, ORDER_STATUS 			STRING
	, ORDER_TIME 			STRING
	, ORBER_FAIL_TIME 		STRING
	, MER_ID 				STRING
	, MER_NAME 				STRING
	, PRODUCT_TYPE 			STRING
	, TXN_TYPE 				STRING
	, TXN_AMT 				DECIMAL(20, 6)
	, CURRENCY 				STRING
	, OPEN_BANK_ID 			STRING
	, OPEN_BANK 			STRING
	, CARD_TYPE 			STRING
	, CARD_NO 				STRING
	, USR_NAME 				STRING
	, CERT_TYPE 			STRING
	, CERT_ID 				STRING
	, PURPOSE 				STRING
	, PRIV1 				STRING
	, STATE 				STRING
	, CITY 					STRING
	, SUB_BANK 				STRING
	, FLAG 					STRING
	, GUARANTY_ID 			STRING
	, STATUS 				STRING
	, CODE 					STRING
	, MESSAGE 				STRING
	, DUE_BILL_NO 			STRING
	, BUSINESS_DATE 		STRING
	, SEND_TIME 			STRING
	, ORI_ORDER_ID 			INT
	, SETUP_DATE 			STRING
	, OPT_DATETIME 			STRING
	, LOAN_USAGE 			STRING
	, PAY_CHANNEL_ID 		STRING
	, PAY_BIZ_CODE 			STRING
	, SUCCESS_AMT 			DECIMAL(20, 6)
	, FAILURE_AMT 			DECIMAL(20, 6)
	, ONLINE_FLAG 			STRING
	, REQUEST_TIME 			STRING
	, SERVICESN 			STRING
	, AUTH_TXN_TERMINAL 	STRING
	, ACQ_ID 				STRING
	, MATCH_IND 			STRING
	, COMPARED_IND 			STRING
	, ERR_IND 				STRING
	, MEMO 					STRING
	, CREATE_TIME 			STRING
	, CREATE_USER 			STRING
	, LST_UPD_TIME 			STRING
	, LST_UPD_USER 			STRING
	, SUB_TERMINAL_TYPE 	STRING
	, CONTR_NBR 			STRING
	, MOBILE_NUMBER 		STRING
	, REF_NBR 				STRING
	, CONTACT_CHNL 			STRING
	, SERVICE_ID 			STRING
	, MERCHANDISE_ORDER 	STRING
	, RESPONSE_CODE 		STRING
	, RESPONSE_MESSAGE 		STRING
	, TERMINAL_DEVICE		STRING
	, PREMIUM_AMT 			DECIMAL(20, 6)
	, PREMIUM_IND 			STRING
	, LOAN_AMT 				DECIMAL(20, 6)
	, COUPON_ID 			STRING
	, OFFSET_TYPE 			STRING
	, TERM 					INT
	, BATCH_ID 				STRING
	, OFF_LINE_REPAY_NO 	STRING
	, IS_PUBLIC_ACCOUNT 	STRING
	, BIGDATA_DEL_STATUS	INT
	, BIGDATA_SYNC_TIME		BIGINT
	, PRIMARY KEY(ORDER_ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.ccs_order_hst(
	ORDER_ID 				INT
	, ORG					STRING
	, CHANNEL_ID 			STRING
	, LOG_KV 				INT
	, ACCT_NBR 				BIGINT
	, ACCT_TYPE 			STRING
	, COMMAND_TYPE 			STRING
	, ORDER_BRIEF 			STRING
	, ORDER_STATUS 			STRING
	, ORDER_TIME 			STRING
	, ORBER_FAIL_TIME 		STRING
	, MER_ID 				STRING
	, MER_NAME 				STRING
	, PRODUCT_TYPE 			STRING
	, TXN_TYPE 				STRING
	, TXN_AMT 				DECIMAL(20, 6)
	, CURRENCY 				STRING
	, OPEN_BANK_ID 			STRING
	, OPEN_BANK 			STRING
	, CARD_TYPE 			STRING
	, CARD_NO 				STRING
	, USR_NAME 				STRING
	, CERT_TYPE 			STRING
	, CERT_ID 				STRING
	, PURPOSE 				STRING
	, PRIV1 				STRING
	, STATE 				STRING
	, CITY 					STRING
	, SUB_BANK 				STRING
	, FLAG 					STRING
	, GUARANTY_ID 			STRING
	, STATUS 				STRING
	, CODE 					STRING
	, MESSAGE 				STRING
	, DUE_BILL_NO 			STRING
	, BUSINESS_DATE 		STRING
	, SEND_TIME 			STRING
	, ORI_ORDER_ID 			INT
	, SETUP_DATE 			STRING
	, OPT_DATETIME 			STRING
	, LOAN_USAGE 			STRING
	, PAY_CHANNEL_ID 		STRING
	, PAY_BIZ_CODE 			STRING
	, SUCCESS_AMT 			DECIMAL(20, 6)
	, FAILURE_AMT 			DECIMAL(20, 6)
	, ONLINE_FLAG 			STRING
	, REQUEST_TIME 			STRING
	, SERVICESN 			STRING
	, AUTH_TXN_TERMINAL 	STRING
	, ACQ_ID 				STRING
	, MATCH_IND 			STRING
	, COMPARED_IND 			STRING
	, ERR_IND 				STRING
	, MEMO 					STRING
	, CREATE_TIME 			STRING
	, CREATE_USER 			STRING
	, LST_UPD_TIME 			STRING
	, LST_UPD_USER 			STRING
	, SUB_TERMINAL_TYPE 	STRING
	, CONTR_NBR 			STRING
	, MOBILE_NUMBER 		STRING
	, REF_NBR 				STRING
	, CONTACT_CHNL 			STRING
	, SERVICE_ID 			STRING
	, MERCHANDISE_ORDER 	STRING
	, RESPONSE_CODE 		STRING
	, RESPONSE_MESSAGE 		STRING
	, TERMINAL_DEVICE		STRING
	, PREMIUM_AMT 			DECIMAL(20, 6)
	, PREMIUM_IND 			STRING
	, LOAN_AMT 				DECIMAL(20, 6)
	, COUPON_ID 			STRING
	, OFFSET_TYPE 			STRING
	, TERM 					INT
	, BATCH_ID 				STRING
	, OFF_LINE_REPAY_NO 	STRING
	, IS_PUBLIC_ACCOUNT 	STRING
	, BIGDATA_DEL_STATUS	INT
	, BIGDATA_SYNC_TIME		BIGINT
	, PRIMARY KEY(ORDER_ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.ccs_overdue_hst_rpt(
	ID 						INT
	, ORG 					STRING
	, CUST_ID 				STRING
	, NAME 					STRING
	, ACCT_NBR 				STRING
	, ACCT_TYPE 			STRING
	, ACCT_TYPE_CN 			STRING
	, LOAN_ID 				INT
	, CREDIT_LMT 			DECIMAL(20, 6)
	, CURR_BAL 				DECIMAL(20, 6)
	, PENALTY_ACRU 			DECIMAL(20, 6)
	, FEE_ACRU 				DECIMAL(20, 6)
	, SVC_ACRU 				DECIMAL(20, 6)
	, OVERDUE_DATE 			STRING
	, OVERDUE_LEVEL 		STRING
	, AGE_CODE 				STRING
	, BATCH_DATE 			STRING
	, CREATE_TIME 			STRING
	, LST_UPD_TIME 			STRING
	, PRODUCT_CODE 			STRING
	, PRODUCT_CN 			STRING
	, LOAN_TYPE 			STRING
	, LOAN_TYPE_CN 			STRING
	, OVERDUE_PRINCIPAL 	DECIMAL(20, 6)
	, OVERDUE_INTEREST 		DECIMAL(20, 6)
	, OVERDUE_PENALTY 		DECIMAL(20, 6)
	, TPL_CHANNEL 			STRING
	, DUE_BILL_NO 			STRING
	, CERT_ID 				STRING
	, ACTIVE_DATE 			STRING
	, LOAN_EXPIRE_DATE 		STRING
	, OVERDUE_DAYS 			DECIMAL(20, 6)
	, LOAN_BAL 				DECIMAL(20, 6)
	, BIGDATA_DEL_STATUS	INT
	, BIGDATA_SYNC_TIME		BIGINT
	, PRIMARY KEY(ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.ccs_loan_bal_rpt(
	ID 						INT
	, ACCT_NBR 				STRING
	, NAME 					STRING
	, CERT_ID 				STRING
	, PRODUCT_CD 			STRING
	, LOAN_INIT_PRIN 		DECIMAL(20, 6)
	, PAID_PRINCIPAL 		DECIMAL(20, 6)
	, LOAN_TERM 			DECIMAL(20, 6)
	, REMAIN_TERM 			DECIMAL(20, 6)
	, OVERDUE_TERM 			DECIMAL(20, 6)
	, OVERDUE_DAYS 			DECIMAL(20, 6)
	, OVERDUE_LEVEL 		STRING
	, IS_SELLTE 			STRING
	, BATCH_DATE 			STRING
	, SELLTE_DATE 			STRING
	, LOAN_DATE 			STRING
	, PURPOSE_DESC 			STRING
	, LOAN_TYPE 			STRING
	, INTEREST_DAY_RATE 	DECIMAL(20, 6)
	, ACCT_EXPIRE_DATE 		STRING
	, DUE_BILL_NO 			STRING
	, BIGDATA_DEL_STATUS	INT
	, BIGDATA_SYNC_TIME		BIGINT
	, PRIMARY KEY(ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

---------------【快乐秒贷表】-------------------------
CREATE TABLE if not exists kudu_sit_ods_prodccsdb.tpl_customer(
	CUST_ID 			STRING
	, BIZ_DATE 			STRING
	, CUST_NAME 		STRING
	, CUST_GENDER 		STRING
	, BIRTH_DATE 		STRING
	, CREATE_DATE 		STRING
	, CUST_STATUS 		STRING
	, ID_TYPE 			STRING
	, ID_NO 			STRING
	, MOBILE_NUMBER 	STRING
	, ADDRESS 			STRING
	, ORG_CHANNEL 		STRING
	, BANK_CARD_NBR 	STRING
	, CREATE_TIME 		STRING
	, CREATE_USER 		STRING
	, LST_UPD_TIME 		STRING
	, LST_UPD_USER 		STRING
	, BIGDATA_DEL_STATUS	INT
	, BIGDATA_SYNC_TIME		BIGINT
	, PRIMARY KEY(CUST_ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.tpl_loan_info(
	DUE_BILL_NO 			STRING
	, BIZ_DATE 				STRING
	, CONTR_NBR 			STRING
	, CUST_ID 				STRING
	, ACTIVE_DATE 			STRING
	, LOAN_STATUS 			STRING
	, PURPOSE 				STRING
	, INTEREST_RATE 		DECIMAL(20, 6)
	, PENALTY_RATE 			DECIMAL(20, 6)
	, LOAN_INIT_PRIN 		DECIMAL(20, 6)
	, LOAN_INIT_INT 		DECIMAL(20, 6)
	, LOAN_INIT_TERM 		DECIMAL(20, 6)
	, LOAN_INIT_FEE 		DECIMAL(20, 6)
	, LOAN_EXPIRE_DATE 		STRING
	, REPAY_MODE 			STRING
	, REPAY_PERIOD 			STRING
	, CURR_TERM 			DECIMAL(20, 6)
	, REMAIN_TERM 			DECIMAL(20, 6)
	, PAID_PRINCIPAL 		DECIMAL(20, 6)
	, PAID_INTEREST 		DECIMAL(20, 6)
	, PAID_FEE 				DECIMAL(20, 6)
	, PAID_PENALTY 			DECIMAL(20, 6)
	, LAST_PMT_DATE 		STRING
	, NEXT_PMT_DATE 		STRING
	, REMAIN_PRIN 			DECIMAL(20, 6)
	, UNSTMT_PRIN 			DECIMAL(20, 6)
	, AGE_CODE 				STRING
	, AGE_HST 				STRING
	, PAYMENT_HST 			STRING
	, FIVE_CLASSIFY 		STRING
	, OVERDUE_IND 			STRING
	, OVERDUE_DAYS 			INT
	, HIG_OVERDUE_DAYS 		INT
	, GRACE_DAYS 			INT
	, CPD_OVERDUE_DATE 		STRING
	, OVERDUE_PRIN 			DECIMAL(20, 6)
	, OVERDUE_INT 			DECIMAL(20, 6)
	, OVERDUE_FEE 			DECIMAL(20, 6)
	, OVERDUE_TERM 			DECIMAL(20, 6)
	, SELLTE_DATE 			STRING
	, OUT_TABLE_INT 		DECIMAL(20, 6)
	, ACCRU_INT_IND 		STRING
	, INTEREST_DAY 			DECIMAL(20, 6)
	, CT_CARD_NBR 			STRING
	, DD_CARD_NBR 			STRING
	, CREATE_TIME 			STRING
	, CREATE_USER 			STRING
	, LST_UPD_TIME 			STRING
	, LST_UPD_USER 			STRING
	, BIGDATA_DEL_STATUS	INT
	, BIGDATA_SYNC_TIME		BIGINT
	, PRIMARY KEY(DUE_BILL_NO)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.tpl_repay_info(
	ID 						INT
	, BIZ_DATE 				STRING
	, CONTRACT_ID 			STRING
	, CUST_ID 				STRING
	, DUE_BILL_NO 			STRING
	, SCHEDULE_ID 			STRING
	, TRADE_DATE 			STRING
	, PAYMENT_TRACE_NBR 	STRING
	, REPAY_MODE 			STRING
	, LOAN_TERM_PRIN 		DECIMAL(20, 6)
	, REPAYMENT_PCL 		DECIMAL(20, 6)
	, LOAN_TERM_INT 		DECIMAL(20, 6)
	, REPAYMENT_IRT 		DECIMAL(20, 6)
	, LOAN_TERM_PEN 		DECIMAL(20, 6)
	, REPAYMENT_PEN 		DECIMAL(20, 6)
	, LOAN_TERM_FEE 		DECIMAL(20, 6)
	, REPAYMENT_FEE 		DECIMAL(20, 6)
	, PAYMENT_TERM 			STRING
	, REMAIN_TERM 			DECIMAL(20, 6)
	, REPAYMENT_TYPE 		STRING
	, TERM_TOTAL_AMT 		DECIMAL(20, 6)
	, TOTAL_AMT 			DECIMAL(20, 6)
	, BIGDATA_DEL_STATUS	INT
	, BIGDATA_SYNC_TIME		BIGINT
	, PRIMARY KEY(ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.tpl_trade_register(
	ID 						INT
	, ORG 					STRING
	, TXN_AMT 				DECIMAL(20, 6)
	, CURRENCY 				STRING
	, DB_CR_IND 			STRING
	, TXN_TYPE 				STRING
	, TXN_STATUS 			STRING
	, TRADE_DATE 			STRING
	, BUSINESS_DATE 		STRING
	, NAME 					STRING
	, CERT_ID 				STRING
	, CT_CARD_NBR 			STRING
	, CT_BANK_ACCT_PHONE 	STRING
	, CT_CARD_BANK_NAME 	STRING
	, CT_CARD_BANK_CODE 	STRING
	, DD_CARD_NBR 			STRING
	, DD_CARD_OPEN_NAME 	STRING
	, DD_BANK_ACCT_PHONE 	STRING
	, DD_CARD_BANK_NAME 	STRING
	, DD_CARD_BANK_CODE 	STRING
	, REF_NBR 				STRING
	, SERVICESN 			STRING
	, CODE 					STRING
	, MESSAGE 				STRING
	, PAY_CHANNEL_ID 		STRING
	, QRY_PAY_RESPCODE 		STRING
	, QRY_CODE 				STRING
	, QRY_MESSAGE 			STRING
	, QRY_UPDATE_DATE 		STRING
	, CREATE_TIME 			STRING
	, CREATE_USER 			STRING
	, LST_UPD_TIME 			STRING
	, LST_UPD_USER 			STRING
	, BIGDATA_DEL_STATUS	INT
	, BIGDATA_SYNC_TIME		BIGINT
	, PRIMARY KEY(ID)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;

CREATE TABLE if not exists kudu_sit_ods_prodccsdb.tpl_txn_register(
	TXN_SEQ 		STRING
	, DUE_BILL_NO 	STRING
	, TXN_AMT 		DECIMAL(20, 6)
	, TOTAL_AMT 	DECIMAL(20, 6)
	, TXN_TYPE 		STRING
	, DB_CR_IND 	STRING
	, CURRENCY 		STRING
	, TRADE_TIME 	STRING
	, BIZ_DATE 		STRING
	, CHANNEL_ID 	STRING
	, PRODUCT_CD 	STRING
	, CREATE_TIME 	STRING
	, CREATE_USER 	STRING
	, LST_UPD_TIME 	STRING
	, LST_UPD_USER 	STRING
	, BIGDATA_DEL_STATUS	INT
	, BIGDATA_SYNC_TIME		BIGINT
	, PRIMARY KEY(TXN_SEQ)
) 
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
;


